project:
  type: website
  output-dir: docs

website:
  title: "How does human activity affect the movement patterns of wild animals?"

format:
  html:
    theme: darkly
    css: custom.css
    toc: true
    toc-title: "Navigation"
    toc-depth: 4
    toc-location: right
    csl: ieee.csl
  pdf: 
    number-sections: true
